---
sudo: required
language: python
services:
  - docker
stages:
  - test
  - name: deploy
    if: branch = develop
jobs:
  include:

    - stage: test
      install:
        - curl -fsSL https://download.docker.com/linux/ubuntu/gpg
          | sudo apt-key add -
        - sudo sh
          -c '. /etc/lsb-release &&
          echo "deb [arch=amd64] https://download.docker.com/linux/ubuntu
          ${DISTRIB_CODENAME} stable"
          > /etc/apt/sources.list.d/docker.list'
        - sudo apt-get update
          -o Dir::Etc::sourcelist=/etc/apt/sources.list.d/docker.list
        - sudo apt-get -y install docker-ce
        - pip install docker-compose
        - docker version
        - docker-compose version
      script:
        - .travis/test.sh
      after_failure:
        - docker-compose logs

    - stage: deploy
      env:
        -
      install: true
      script: true
      before_deploy:
        - mkdir -p ~/.ssh &&
          chmod 700 ~/.ssh &&
          chmod 400 ~/.ssh/id_ed25519
        - openssl aes-256-cbc -K $encrypted_1fc90f464345_key
          -iv $encrypted_1fc90f464345_iv -in .travis/id_ed25519.enc
          -out ~/.ssh/id_ed25519 -d
      deploy:
        - provider: script
          script: bash .travis/deploy.sh
          on:
            branch: develop

branches:
  except:
    - master
# notifications:
#   slack:
#     rooms:
#       secure: <EMPTY>
#   on_success: always
#   on_failure: always
