---
version: '3.6'
services:
  shell:
    hostname: shell
    build: .
    image: cmeza99/container-shell:develop
    volumes:
      - type: bind
        source: ./SHARED
        target: /shared
      - type: volume
        source: home_data
        target: /home

volumes:
  home_data:
