---
version: '3.6'
services:
  home:
    hostname: shell
    build: .
    image: cmeza99/container-shell
    volumes:
      - type: bind
        source: ./SHARED
        target: /root/SHARED
      - type: volume
        source: root_data
        target: /root

volumes:
  root_data:
