---
version: '3.6'
services:
  home:
    hostname: home
    build: .
    image: digitalr00ts/home
    volumes:
      - type: bind
        source: ./SHARED
        target: /root/SHARED
      - type: volume
        source: root_data
        target: /root

volumes:
  root_data:
